import re

with open('pipeline.py', 'r', encoding='utf-8') as f:
    text = f.read()

correct_block = r'''    QWEN3 MULTI-TURN JSON SCHEMA:
    ```json
    [
      {
        "training_data_id": "Auto-generated by json_aggregator.py. Format: TD-{TYPE}-{STD}-T{N}t{K}-{DATE}-v{VER}. Example: TD-COD-PAS8800-T3t1-20260322-v1.0",
        "prompt_version": "Auto-set by json_aggregator.py. Format: CodingTasks_v{VER}. Example: CodingTasks_v1.0",
        "model_used_generation": "Auto-detected: actual inference model name (default: gemini-2.5-pro). Override via MODEL_NAME env var.",
        "knowledge_source_date": "Extract Publication Date YYYY-MM-DD from the document, or write Unknown",
        "document": "The exact title of the source document",
        "task_type": "coding_task",
        "affected_role": "The specific engineering role assigned from the variation schema",
        "date_of_generation": "Today's Date YYYY-MM-DD",
        "key_words": ["A technical keyword", "Another technical keyword", "A third technical keyword"],
        "summary": "A concise, one-sentence, highly technical summary of the generated coding problem",
        "difficulty": "An integer string between 65 and 100 representing the extreme complexity",
        "evaluation_criteria": ["A strict technical pass/fail criterion", "Another strict technical criterion"],
        "conversations": [
          {
            "role": "user",
            "content": "[Thinking] An immersive, in-character 3-paragraph problem statement from the assigned role, demanding a >400 line code implementation. The problem is strictly built around the theoretical concepts of the document, naturally applying the exact Meta-Strategy assigned in the variation instructions without breaking the fourth wall."
          },
          {
            "role": "assistant",
            "reasoning": "The complete, 10000+ character internal monologue strictly following the 8-step template provided above, enclosed in <think> and </think> tags.",
            "content": "A fully escaped JSON string representing an object with the following keys: 'formal_requirements' (an array of objects containing req_id, description, and pass_criteria), 'architecture_block' (a massive PlantUML or Mermaid syntax diagram detailing the software structure), 'executable_code' (a massive string of 400+ lines of production code, fully commented, tracing back to the req_ids), 'usage_examples' (typical and edge case invocation code), 'testbench_and_mocks' (detailed build/run specs and mock data structures), and 'test_criteria' (an exhaustive array of boundary/NaN/Inf test strings)."
          },
          {
            "role": "user",
            "content": "[No Thinking] A highly technical, in-character follow-up question regarding how a specific edge case is handled by the algorithmic bounds of the generated code."
          },
          {
            "role": "assistant",
            "reasoning": "<think></think> (Instruction: Because the key word [No Thinking] is set, keep the content empty between the think tags.)",
            "content": "A brief, highly technical plaintext answer directly addressing the edge-case handling mechanism."
          },
          {
            "role": "user",
            "content": "[No Thinking] An in-character follow-up question probing the memory optimization, Big-O scaling, or hardware latencies of the chosen architecture."
          },
          {
            "role": "assistant",
            "reasoning": "<think></think> (Instruction: Because the key word [No Thinking] is set, keep the content empty between the think tags.)",
            "content": "A brief, highly technical plaintext answer justifying the memory and algorithmic scaling."
          }
        ]
      }
    ]
    ```'''

# We need to escape braces for python's f-string in `pipeline.py`
correct_block = correct_block.replace('{', '{{').replace('}', '}}')

pattern = re.compile(r'    QWEN3 MULTI-TURN JSON SCHEMA:.*?(?=\s+THE 8-STEP MONOLOGUE TEMPLATE)', re.DOTALL)

new_text, count = pattern.subn(correct_block, text)

if count > 0:
    with open('pipeline.py', 'w', encoding='utf-8') as f:
        f.write(new_text)
    print('Pipeline successfully updated.')
else:
    print('Error: Could not find block in pipeline.py!')
